import Foundation

/// Writes a `docker-compose.override.yml` next to the service's compose file so
/// every container in that project gets a CPU/RAM cap matching the chosen tier.
public enum ResourceTierOverride {
    public static func write(for service: Service) {
        let dir = URL(fileURLWithPath: service.folderPath)
        let override = dir.appendingPathComponent("docker-compose.override.yml")
        let yaml = yaml(for: service.resourceTier, primaryServiceName: service.slug)
        try? yaml.write(to: override, atomically: true, encoding: .utf8)
    }

    public static func clear(for service: Service) {
        let url = URL(fileURLWithPath: service.folderPath).appendingPathComponent("docker-compose.override.yml")
        try? FileManager.default.removeItem(at: url)
    }

    private static func yaml(for tier: ResourceTier, primaryServiceName: String) -> String {
        let (cpus, memory): (String, String) = {
            switch tier {
            case .light: return ("0.5", "512m")
            case .normal: return ("2", "2g")
            case .heavy: return ("6", "6g")
            }
        }()
        // Compose v2 honors `deploy.resources.limits` outside swarm mode for
        // limits. We target the main service (which by catalog convention is
        // named after the slug).
        return """
        # Generated by LazyOS — resource tier: \(tier.label) (\(tier.detail))
        services:
          \(primaryServiceName):
            deploy:
              resources:
                limits:
                  cpus: "\(cpus)"
                  memory: "\(memory)"
        """
    }
}
